#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.1.0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'padlen': 1,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'verbosity': 30}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_83131ce6e3291b77c5454fd855de8989a6d98134





ufc_finite_element element_83131ce6e3291b77c5454fd855de8989a6d98134 =
{
  .signature = "FiniteElement('Lagrange', triangle, 1)",
  .cell_shape = triangle,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 3,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 1,

  .needs_transformation_data = 0,
  .interpolation_is_identity = 1,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_83131ce6e3291b77c5454fd855de8989a6d98134

// Code for element element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4

int value_shape_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4[1] = { 2 };
int reference_value_shape_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4[1] = { 2 };
ufc_finite_element* sub_elements_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4[2] = { &element_83131ce6e3291b77c5454fd855de8989a6d98134, &element_83131ce6e3291b77c5454fd855de8989a6d98134 };

ufc_finite_element element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)",
  .cell_shape = triangle,
  .topological_dimension = 2,
  .geometric_dimension = 2,
  .space_dimension = 6,
  .value_rank = 1,
  .value_shape = value_shape_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4,
  .value_size = 2,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4,
  .reference_value_size = 2,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 2,

  .needs_transformation_data = 0,
  .interpolation_is_identity = 1,

  .num_sub_elements = 2,
  .sub_elements = sub_elements_element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4
};

// End of code for element element_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4

// Code for dofmap dofmap_83131ce6e3291b77c5454fd855de8989a6d98134



void tabulate_entity_dofs_dofmap_83131ce6e3291b77c5454fd855de8989a6d98134(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_83131ce6e3291b77c5454fd855de8989a6d98134 =
{
  .signature = "FFCx dofmap for FiniteElement('Lagrange', triangle, 1)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_83131ce6e3291b77c5454fd855de8989a6d98134,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_83131ce6e3291b77c5454fd855de8989a6d98134

// Code for dofmap dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4

ufc_dofmap* sub_dofmaps_dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4[2] = { &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134, &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134 };

void tabulate_entity_dofs_dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4 =
{
  .signature = "FFCx dofmap for VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)",
  .block_size = 2,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 3,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4,
  .num_sub_dofmaps = 2,
  .sub_dofmaps = sub_dofmaps_dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4
};

// End of code for dofmap dofmap_8975034e89451e69e1c0d41ae7ccd3a1a4dcc5d4

// Code for integral integral_8332eefb30b220c57e616e858f55d3818a46e0cd

void tabulate_tensor_integral_8332eefb30b220c57e616e858f55d3818a46e0cd(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_083[1] = { 0.5 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE3_C0_D01_Q083[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    static const double FE3_C0_D10_Q083[1][1][1][3] = { { { { -1.0, 1.0, 0.0 } } } };
    // Quadrature loop independent computations for quadrature rule 083
    const double J_c0 = coordinate_dofs[0] * FE3_C0_D10_Q083[0][0][0][0] + coordinate_dofs[2] * FE3_C0_D10_Q083[0][0][0][1] + coordinate_dofs[4] * FE3_C0_D10_Q083[0][0][0][2];
    const double J_c3 = coordinate_dofs[1] * FE3_C0_D01_Q083[0][0][0][0] + coordinate_dofs[3] * FE3_C0_D01_Q083[0][0][0][1] + coordinate_dofs[5] * FE3_C0_D01_Q083[0][0][0][2];
    const double J_c1 = coordinate_dofs[0] * FE3_C0_D01_Q083[0][0][0][0] + coordinate_dofs[2] * FE3_C0_D01_Q083[0][0][0][1] + coordinate_dofs[4] * FE3_C0_D01_Q083[0][0][0][2];
    const double J_c2 = coordinate_dofs[1] * FE3_C0_D10_Q083[0][0][0][0] + coordinate_dofs[3] * FE3_C0_D10_Q083[0][0][0][1] + coordinate_dofs[5] * FE3_C0_D10_Q083[0][0][0][2];
    ufc_scalar_t sp_083[20];
    sp_083[0] = J_c0 * J_c3;
    sp_083[1] = J_c1 * J_c2;
    sp_083[2] = sp_083[0] + -1 * sp_083[1];
    sp_083[3] = J_c0 / sp_083[2];
    sp_083[4] = (-1 * J_c1) / sp_083[2];
    sp_083[5] = sp_083[3] * sp_083[3];
    sp_083[6] = sp_083[3] * sp_083[4];
    sp_083[7] = sp_083[4] * sp_083[4];
    sp_083[8] = J_c3 / sp_083[2];
    sp_083[9] = (-1 * J_c2) / sp_083[2];
    sp_083[10] = sp_083[9] * sp_083[9];
    sp_083[11] = sp_083[8] * sp_083[9];
    sp_083[12] = sp_083[8] * sp_083[8];
    sp_083[13] = sp_083[5] + sp_083[10];
    sp_083[14] = sp_083[6] + sp_083[11];
    sp_083[15] = sp_083[12] + sp_083[7];
    sp_083[16] = fabs(sp_083[2]);
    sp_083[17] = sp_083[13] * sp_083[16];
    sp_083[18] = sp_083[14] * sp_083[16];
    sp_083[19] = sp_083[15] * sp_083[16];
    for (int iq = 0; iq < 1; ++iq)
    {
        const ufc_scalar_t fw0 = sp_083[19] * weights_083[iq];
        const ufc_scalar_t fw1 = sp_083[18] * weights_083[iq];
        const ufc_scalar_t fw2 = sp_083[17] * weights_083[iq];
        ufc_scalar_t t0[3];
        ufc_scalar_t t1[3];
        for (int i = 0; i < 3; ++i)
        {
            t0[i] = fw0 * FE3_C0_D10_Q083[0][0][0][i] + fw1 * FE3_C0_D01_Q083[0][0][0][i];
            t1[i] = fw1 * FE3_C0_D10_Q083[0][0][0][i] + fw2 * FE3_C0_D01_Q083[0][0][0][i];
        }
        for (int i = 0; i < 3; ++i)
        {
            for (int j = 0; j < 3; ++j)
            {
                ufc_scalar_t acc0 = 0;
                acc0 += FE3_C0_D10_Q083[0][0][0][j] * t0[i];
                acc0 += FE3_C0_D01_Q083[0][0][0][j] * t1[i];
                A[3 * i + j] += acc0;
            }
        }
    }
}



ufc_integral integral_8332eefb30b220c57e616e858f55d3818a46e0cd =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_8332eefb30b220c57e616e858f55d3818a46e0cd,
  .needs_transformation_data = 0
};

// End of code for integral integral_8332eefb30b220c57e616e858f55d3818a46e0cd

// Code for form form_1e2bfd8b8eac1148270169861adc8d1d41cc225e


ufc_dofmap* dofmaps_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e[2] = { &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134, &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134 };
ufc_finite_element* finite_elements_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e[2] = { &element_83131ce6e3291b77c5454fd855de8989a6d98134, &element_83131ce6e3291b77c5454fd855de8989a6d98134 };

// Return a list of the coefficient names.
const char** coefficient_name_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(void)
{
return NULL;
}

int* integral_ids_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e;
default:
    return NULL;
}
}

int num_integrals_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e[1] = { &integral_8332eefb30b220c57e616e858f55d3818a46e0cd };
switch (integral_type)
{
case cell:
    return integrals_cell_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e;
default:
    return NULL;
}
}

ufc_form form_1e2bfd8b8eac1148270169861adc8d1d41cc225e =
{

  .signature = "ce26b0e24fae604fc9c102aa2255fc8942822ef3358564be2e04340dc6d2a14e43a32892995077cd83f53e0d7b026df7e460cd9f1f5a0ee6b6e11406db961a8a",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,
  .constant_name_map = constant_name_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,

  .finite_elements = finite_elements_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,
  .dofmaps = dofmaps_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,

  .integral_ids = integral_ids_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,
  .num_integrals = num_integrals_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e,

  .integrals = integrals_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e
};

// Alias name
ufc_form* form_libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c_0 = &form_1e2bfd8b8eac1148270169861adc8d1d41cc225e;

ufc_function_space* functionspace_form_libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c_0(const char* function_name)
{
static ufc_function_space functionspace_v_0 =
{
.finite_element = &element_83131ce6e3291b77c5454fd855de8989a6d98134,
.dofmap = &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_v_1 =
{
.finite_element = &element_83131ce6e3291b77c5454fd855de8989a6d98134,
.dofmap = &dofmap_83131ce6e3291b77c5454fd855de8989a6d98134,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v_0") == 0)
    return &functionspace_v_0;
else if (strcmp(function_name, "v_1") == 0)
    return &functionspace_v_1;
return NULL;

}

// End of code for form form_1e2bfd8b8eac1148270169861adc8d1d41cc225e


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 38), // char const * *()(void)
/*  1 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION, 31), // int *()(ufc_integral_type)
/*  3 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufc_integral_type
/*  4 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  5 */ _CFFI_OP(_CFFI_OP_FUNCTION, 25), // int()(ufc_integral_type)
/*  6 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 55), // ufc_integral * *()(ufc_integral_type)
/*  9 */ _CFFI_OP(_CFFI_OP_NOOP, 3),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 11 */ _CFFI_OP(_CFFI_OP_FUNCTION, 63), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *, uint32_t)
/* 12 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // double *
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // double const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 16 */ _CFFI_OP(_CFFI_OP_POINTER, 25), // int const *
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 59), // uint8_t const *
/* 18 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 22), // uint32_t
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 20 */ _CFFI_OP(_CFFI_OP_FUNCTION, 63), // void()(double *, double const *, double const *, double const *, int, double const *, double const *, double const *)
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 12),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 25 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 26 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 27 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 28 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 30 */ _CFFI_OP(_CFFI_OP_FUNCTION, 63), // void()(int *, int, int)
/* 31 */ _CFFI_OP(_CFFI_OP_POINTER, 25), // int *
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 35 */ _CFFI_OP(_CFFI_OP_POINTER, 36), // _Bool const *
/* 36 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 37 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // char const * *(*)(void)
/* 38 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // char const * *
/* 39 */ _CFFI_OP(_CFFI_OP_POINTER, 40), // char const *
/* 40 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 41 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 42 */ _CFFI_OP(_CFFI_OP_POINTER, 2), // int *(*)(ufc_integral_type)
/* 43 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int(*)(ufc_integral_type)
/* 44 */ _CFFI_OP(_CFFI_OP_ARRAY, 25), // int[4]
/* 45 */ (_cffi_opcode_t)(4),
/* 46 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufc_custom_integral
/* 47 */ _CFFI_OP(_CFFI_OP_POINTER, 48), // ufc_dofmap * *
/* 48 */ _CFFI_OP(_CFFI_OP_POINTER, 49), // ufc_dofmap *
/* 49 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufc_dofmap
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufc_finite_element * *
/* 51 */ _CFFI_OP(_CFFI_OP_POINTER, 52), // ufc_finite_element *
/* 52 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // ufc_finite_element
/* 53 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // ufc_form
/* 54 */ _CFFI_OP(_CFFI_OP_POINTER, 8), // ufc_integral * *(*)(ufc_integral_type)
/* 55 */ _CFFI_OP(_CFFI_OP_POINTER, 56), // ufc_integral * *
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 57), // ufc_integral *
/* 57 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // ufc_integral
/* 58 */ _CFFI_OP(_CFFI_OP_ENUM, 1), // ufc_shape
/* 59 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 60 */ _CFFI_OP(_CFFI_OP_POINTER, 11), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *, uint32_t)
/* 61 */ _CFFI_OP(_CFFI_OP_POINTER, 20), // void(*)(double *, double const *, double const *, double const *, int, double const *, double const *, double const *)
/* 62 */ _CFFI_OP(_CFFI_OP_POINTER, 30), // void(*)(int *, int, int)
/* 63 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_interval(unsigned long long *o)
{
  int n = (interval) <= 0;
  *o = (unsigned long long)((interval) | 0);  /* check that interval is an integer */
  return n;
}

static int _cffi_const_triangle(unsigned long long *o)
{
  int n = (triangle) <= 0;
  *o = (unsigned long long)((triangle) | 0);  /* check that triangle is an integer */
  return n;
}

static int _cffi_const_quadrilateral(unsigned long long *o)
{
  int n = (quadrilateral) <= 0;
  *o = (unsigned long long)((quadrilateral) | 0);  /* check that quadrilateral is an integer */
  return n;
}

static int _cffi_const_tetrahedron(unsigned long long *o)
{
  int n = (tetrahedron) <= 0;
  *o = (unsigned long long)((tetrahedron) | 0);  /* check that tetrahedron is an integer */
  return n;
}

static int _cffi_const_hexahedron(unsigned long long *o)
{
  int n = (hexahedron) <= 0;
  *o = (unsigned long long)((hexahedron) | 0);  /* check that hexahedron is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_custom_integral(ufc_custom_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int, double const *, double const *, double const *) = &p->tabulate_tensor; (void)tmp; }
  (void)((p->needs_transformation_data) | 0);  /* check that 'ufc_custom_integral.needs_transformation_data' is an integer */
}
struct _cffi_align__ufc_custom_integral { char x; ufc_custom_integral y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_dofmap(ufc_dofmap *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->num_global_support_dofs) | 0);  /* check that 'ufc_dofmap.num_global_support_dofs' is an integer */
  (void)((p->num_element_support_dofs) | 0);  /* check that 'ufc_dofmap.num_element_support_dofs' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufc_dofmap.block_size' is an integer */
  { int(*tmp)[4] = &p->num_entity_dofs; (void)tmp; }
  { void(* *tmp)(int *, int, int) = &p->tabulate_entity_dofs; (void)tmp; }
  (void)((p->num_sub_dofmaps) | 0);  /* check that 'ufc_dofmap.num_sub_dofmaps' is an integer */
  { ufc_dofmap * * *tmp = &p->sub_dofmaps; (void)tmp; }
}
struct _cffi_align__ufc_dofmap { char x; ufc_dofmap y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_finite_element(ufc_finite_element *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  { ufc_shape *tmp = &p->cell_shape; (void)tmp; }
  (void)((p->topological_dimension) | 0);  /* check that 'ufc_finite_element.topological_dimension' is an integer */
  (void)((p->geometric_dimension) | 0);  /* check that 'ufc_finite_element.geometric_dimension' is an integer */
  (void)((p->space_dimension) | 0);  /* check that 'ufc_finite_element.space_dimension' is an integer */
  (void)((p->value_rank) | 0);  /* check that 'ufc_finite_element.value_rank' is an integer */
  { int * *tmp = &p->value_shape; (void)tmp; }
  (void)((p->value_size) | 0);  /* check that 'ufc_finite_element.value_size' is an integer */
  (void)((p->reference_value_rank) | 0);  /* check that 'ufc_finite_element.reference_value_rank' is an integer */
  { int * *tmp = &p->reference_value_shape; (void)tmp; }
  (void)((p->reference_value_size) | 0);  /* check that 'ufc_finite_element.reference_value_size' is an integer */
  (void)((p->degree) | 0);  /* check that 'ufc_finite_element.degree' is an integer */
  (void)((p->block_size) | 0);  /* check that 'ufc_finite_element.block_size' is an integer */
  { char const * *tmp = &p->family; (void)tmp; }
  (void)((p->num_sub_elements) | 0);  /* check that 'ufc_finite_element.num_sub_elements' is an integer */
  (void)((p->needs_transformation_data) | 0);  /* check that 'ufc_finite_element.needs_transformation_data' is an integer */
  (void)((p->interpolation_is_identity) | 0);  /* check that 'ufc_finite_element.interpolation_is_identity' is an integer */
  { ufc_finite_element * * *tmp = &p->sub_elements; (void)tmp; }
}
struct _cffi_align__ufc_finite_element { char x; ufc_finite_element y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_form(ufc_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufc_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufc_form.num_coefficients' is an integer */
  (void)((p->num_constants) | 0);  /* check that 'ufc_form.num_constants' is an integer */
  { int * *tmp = &p->original_coefficient_position; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->coefficient_name_map; (void)tmp; }
  { char const * *(* *tmp)(void) = &p->constant_name_map; (void)tmp; }
  { ufc_finite_element * * *tmp = &p->finite_elements; (void)tmp; }
  { ufc_dofmap * * *tmp = &p->dofmaps; (void)tmp; }
  { int *(* *tmp)(ufc_integral_type) = &p->integral_ids; (void)tmp; }
  { int(* *tmp)(ufc_integral_type) = &p->num_integrals; (void)tmp; }
  { ufc_integral * *(* *tmp)(ufc_integral_type) = &p->integrals; (void)tmp; }
}
struct _cffi_align__ufc_form { char x; ufc_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufc_integral(ufc_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *, uint32_t) = &p->tabulate_tensor; (void)tmp; }
  (void)((p->needs_transformation_data) | 0);  /* check that 'ufc_integral.needs_transformation_data' is an integer */
}
struct _cffi_align__ufc_integral { char x; ufc_integral y; };

static ufc_form *_cffi_var_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e(void)
{
  return &(form_1e2bfd8b8eac1148270169861adc8d1d41cc225e);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_1e2bfd8b8eac1148270169861adc8d1d41cc225e", (void *)_cffi_var_form_1e2bfd8b8eac1148270169861adc8d1d41cc225e, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 53), (void *)0 },
  { "hexahedron", (void *)_cffi_const_hexahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "interval", (void *)_cffi_const_interval, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "quadrilateral", (void *)_cffi_const_quadrilateral, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "tetrahedron", (void *)_cffi_const_tetrahedron, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "triangle", (void *)_cffi_const_triangle, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "enabled_coefficients", offsetof(ufc_custom_integral, enabled_coefficients),
                            sizeof(((ufc_custom_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "tabulate_tensor", offsetof(ufc_custom_integral, tabulate_tensor),
                       sizeof(((ufc_custom_integral *)0)->tabulate_tensor),
                       _CFFI_OP(_CFFI_OP_NOOP, 61) },
  { "needs_transformation_data", offsetof(ufc_custom_integral, needs_transformation_data),
                                 sizeof(((ufc_custom_integral *)0)->needs_transformation_data),
                                 _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "signature", offsetof(ufc_dofmap, signature),
                 sizeof(((ufc_dofmap *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "num_global_support_dofs", offsetof(ufc_dofmap, num_global_support_dofs),
                               sizeof(((ufc_dofmap *)0)->num_global_support_dofs),
                               _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "num_element_support_dofs", offsetof(ufc_dofmap, num_element_support_dofs),
                                sizeof(((ufc_dofmap *)0)->num_element_support_dofs),
                                _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "block_size", offsetof(ufc_dofmap, block_size),
                  sizeof(((ufc_dofmap *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "num_entity_dofs", offsetof(ufc_dofmap, num_entity_dofs),
                       sizeof(((ufc_dofmap *)0)->num_entity_dofs),
                       _CFFI_OP(_CFFI_OP_NOOP, 44) },
  { "tabulate_entity_dofs", offsetof(ufc_dofmap, tabulate_entity_dofs),
                            sizeof(((ufc_dofmap *)0)->tabulate_entity_dofs),
                            _CFFI_OP(_CFFI_OP_NOOP, 62) },
  { "num_sub_dofmaps", offsetof(ufc_dofmap, num_sub_dofmaps),
                       sizeof(((ufc_dofmap *)0)->num_sub_dofmaps),
                       _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "sub_dofmaps", offsetof(ufc_dofmap, sub_dofmaps),
                   sizeof(((ufc_dofmap *)0)->sub_dofmaps),
                   _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "signature", offsetof(ufc_finite_element, signature),
                 sizeof(((ufc_finite_element *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "cell_shape", offsetof(ufc_finite_element, cell_shape),
                  sizeof(((ufc_finite_element *)0)->cell_shape),
                  _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "topological_dimension", offsetof(ufc_finite_element, topological_dimension),
                             sizeof(((ufc_finite_element *)0)->topological_dimension),
                             _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "geometric_dimension", offsetof(ufc_finite_element, geometric_dimension),
                           sizeof(((ufc_finite_element *)0)->geometric_dimension),
                           _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "space_dimension", offsetof(ufc_finite_element, space_dimension),
                       sizeof(((ufc_finite_element *)0)->space_dimension),
                       _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "value_rank", offsetof(ufc_finite_element, value_rank),
                  sizeof(((ufc_finite_element *)0)->value_rank),
                  _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "value_shape", offsetof(ufc_finite_element, value_shape),
                   sizeof(((ufc_finite_element *)0)->value_shape),
                   _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "value_size", offsetof(ufc_finite_element, value_size),
                  sizeof(((ufc_finite_element *)0)->value_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "reference_value_rank", offsetof(ufc_finite_element, reference_value_rank),
                            sizeof(((ufc_finite_element *)0)->reference_value_rank),
                            _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "reference_value_shape", offsetof(ufc_finite_element, reference_value_shape),
                             sizeof(((ufc_finite_element *)0)->reference_value_shape),
                             _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "reference_value_size", offsetof(ufc_finite_element, reference_value_size),
                            sizeof(((ufc_finite_element *)0)->reference_value_size),
                            _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "degree", offsetof(ufc_finite_element, degree),
              sizeof(((ufc_finite_element *)0)->degree),
              _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "block_size", offsetof(ufc_finite_element, block_size),
                  sizeof(((ufc_finite_element *)0)->block_size),
                  _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "family", offsetof(ufc_finite_element, family),
              sizeof(((ufc_finite_element *)0)->family),
              _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "num_sub_elements", offsetof(ufc_finite_element, num_sub_elements),
                        sizeof(((ufc_finite_element *)0)->num_sub_elements),
                        _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "needs_transformation_data", offsetof(ufc_finite_element, needs_transformation_data),
                                 sizeof(((ufc_finite_element *)0)->needs_transformation_data),
                                 _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "interpolation_is_identity", offsetof(ufc_finite_element, interpolation_is_identity),
                                 sizeof(((ufc_finite_element *)0)->interpolation_is_identity),
                                 _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "sub_elements", offsetof(ufc_finite_element, sub_elements),
                    sizeof(((ufc_finite_element *)0)->sub_elements),
                    _CFFI_OP(_CFFI_OP_NOOP, 50) },
  { "signature", offsetof(ufc_form, signature),
                 sizeof(((ufc_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 39) },
  { "rank", offsetof(ufc_form, rank),
            sizeof(((ufc_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "num_coefficients", offsetof(ufc_form, num_coefficients),
                        sizeof(((ufc_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "num_constants", offsetof(ufc_form, num_constants),
                     sizeof(((ufc_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 25) },
  { "original_coefficient_position", offsetof(ufc_form, original_coefficient_position),
                                     sizeof(((ufc_form *)0)->original_coefficient_position),
                                     _CFFI_OP(_CFFI_OP_NOOP, 31) },
  { "coefficient_name_map", offsetof(ufc_form, coefficient_name_map),
                            sizeof(((ufc_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "constant_name_map", offsetof(ufc_form, constant_name_map),
                         sizeof(((ufc_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "finite_elements", offsetof(ufc_form, finite_elements),
                       sizeof(((ufc_form *)0)->finite_elements),
                       _CFFI_OP(_CFFI_OP_NOOP, 50) },
  { "dofmaps", offsetof(ufc_form, dofmaps),
               sizeof(((ufc_form *)0)->dofmaps),
               _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "integral_ids", offsetof(ufc_form, integral_ids),
                    sizeof(((ufc_form *)0)->integral_ids),
                    _CFFI_OP(_CFFI_OP_NOOP, 42) },
  { "num_integrals", offsetof(ufc_form, num_integrals),
                     sizeof(((ufc_form *)0)->num_integrals),
                     _CFFI_OP(_CFFI_OP_NOOP, 43) },
  { "integrals", offsetof(ufc_form, integrals),
                 sizeof(((ufc_form *)0)->integrals),
                 _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "enabled_coefficients", offsetof(ufc_integral, enabled_coefficients),
                            sizeof(((ufc_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 35) },
  { "tabulate_tensor", offsetof(ufc_integral, tabulate_tensor),
                       sizeof(((ufc_integral *)0)->tabulate_tensor),
                       _CFFI_OP(_CFFI_OP_NOOP, 60) },
  { "needs_transformation_data", offsetof(ufc_integral, needs_transformation_data),
                                 sizeof(((ufc_integral *)0)->needs_transformation_data),
                                 _CFFI_OP(_CFFI_OP_NOOP, 36) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufc_custom_integral", 46, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_custom_integral), offsetof(struct _cffi_align__ufc_custom_integral, y), 0, 3 },
  { "ufc_dofmap", 49, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_dofmap), offsetof(struct _cffi_align__ufc_dofmap, y), 3, 8 },
  { "ufc_finite_element", 52, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_finite_element), offsetof(struct _cffi_align__ufc_finite_element, y), 11, 18 },
  { "ufc_form", 53, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_form), offsetof(struct _cffi_align__ufc_form, y), 29, 12 },
  { "ufc_integral", 57, _CFFI_F_CHECK_FIELDS,
    sizeof(ufc_integral), offsetof(struct _cffi_align__ufc_integral, y), 41, 3 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufc_integral_type", 3, _cffi_prim_int(sizeof(ufc_integral_type), ((ufc_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet" },
  { "$ufc_shape", 58, _cffi_prim_int(sizeof(ufc_shape), ((ufc_shape)-1) <= 0),
    "interval,triangle,quadrilateral,tetrahedron,hexahedron,vertex" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufc_custom_integral", 46 },
  { "ufc_dofmap", 49 },
  { "ufc_finite_element", 52 },
  { "ufc_form", 53 },
  { "ufc_integral", 57 },
  { "ufc_integral_type", 3 },
  { "ufc_scalar_t", 41 },
  { "ufc_shape", 58 },
  { "ufc_tabulate_tensor", 11 },
  { "ufc_tabulate_tensor_custom", 20 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  10,  /* num_globals */
  5,  /* num_struct_unions */
  2,  /* num_enums */
  10,  /* num_typenames */
  NULL,  /* no includes */
  64,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c(void) { return NULL; }
#  else
     initlibffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c(void)
{
  return _cffi_init("libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c(void)
{
  _cffi_init("libffcx_forms_9f5a2705274be37170131053b59d4158a6cb8e3c", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
