// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'uflacs',
//   'scalar_type': 'double',
//   'timeout': 10}


#pragma once

typedef double fenics_scalar_t;
#include <fenics_interface.h>

#ifdef __cplusplus
extern "C" {
#endif

fenics_finite_element* create_ffc_element_61ff161f181d8d25c3f5eb55e90a5648e302a1ed_finite_element_main(void);

fenics_finite_element* create_ffc_element_c36d98ed53a91e1d115908d2181c9c6a227d2889_finite_element_main(void);

fenics_dofmap* create_ffc_element_61ff161f181d8d25c3f5eb55e90a5648e302a1ed_dofmap_main(void);

fenics_dofmap* create_ffc_element_c36d98ed53a91e1d115908d2181c9c6a227d2889_dofmap_main(void);

fenics_coordinate_mapping* create_ffc_coordinate_mapping_73cbcf4c68eb877db68d82df32b26e26d95c510b_coordinate_mapping_main(void);

fenics_integral* create_hyperelasticity_cell_integral_f4020f86f88b33ba35b03dd6a479dd225f8cc846_otherwise(void);

fenics_integral* create_hyperelasticity_cell_integral_89791d72bd3c84c774f554d107412434dc965b01_otherwise(void);

fenics_integral* create_hyperelasticity_exterior_facet_integral_89791d72bd3c84c774f554d107412434dc965b01_otherwise(void);

fenics_form* create_hyperelasticity_form_f4020f86f88b33ba35b03dd6a479dd225f8cc846(void);

fenics_form* create_hyperelasticity_form_89791d72bd3c84c774f554d107412434dc965b01(void);


// Typedefs for convenience pointers to functions (factories)
typedef fenics_function_space* (*fenics_function_space_factory_ptr)(void);
typedef fenics_form* (*fenics_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 3)
fenics_function_space* HyperElasticity_coefficientspace_B_create(void);
fenics_function_space* HyperElasticity_coefficientspace_T_create(void);
fenics_function_space* HyperElasticity_coefficientspace_u_create(void);

// Form function spaces helpers (form 'a')
fenics_function_space* HyperElasticity_form_a_functionspace_0_create(void);

fenics_function_space* HyperElasticity_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
static const fenics_function_space_factory_ptr HyperElasticity_form_a_functionspace_2_create = HyperElasticity_coefficientspace_u_create;
/*    Form helper */
static const fenics_form_factory_ptr HyperElasticity_form_a_create = create_hyperelasticity_form_f4020f86f88b33ba35b03dd6a479dd225f8cc846;

/*    Typedefs (function spaces for form_a) */
static const fenics_function_space_factory_ptr HyperElasticity_form_a_testspace_create = HyperElasticity_form_a_functionspace_0_create;
static const fenics_function_space_factory_ptr HyperElasticity_form_a_trialspace_create = HyperElasticity_form_a_functionspace_1_create;
// static fenics_function_space_factory_ptr HyperElasticity_form_a_coefficientspace_u_create = HyperElasticity_form_a__functionspace_2_create;

 /* End coefficient typedefs */

// Form function spaces helpers (form 'L')
fenics_function_space* HyperElasticity_form_L_functionspace_0_create(void);

/* Coefficient function space typedefs for form "form_L" */
static const fenics_function_space_factory_ptr HyperElasticity_form_L_functionspace_1_create = HyperElasticity_coefficientspace_u_create;
static const fenics_function_space_factory_ptr HyperElasticity_form_L_functionspace_2_create = HyperElasticity_coefficientspace_B_create;
static const fenics_function_space_factory_ptr HyperElasticity_form_L_functionspace_3_create = HyperElasticity_coefficientspace_T_create;
/*    Form helper */
static const fenics_form_factory_ptr HyperElasticity_form_L_create = create_hyperelasticity_form_89791d72bd3c84c774f554d107412434dc965b01;

/*    Typedefs (function spaces for form_L) */
static const fenics_function_space_factory_ptr HyperElasticity_form_L_testspace_create = HyperElasticity_form_L_functionspace_0_create;
// static fenics_function_space_factory_ptr HyperElasticity_form_L_coefficientspace_u_create = HyperElasticity_form_L__functionspace_1_create;
// static fenics_function_space_factory_ptr HyperElasticity_form_L_coefficientspace_B_create = HyperElasticity_form_L__functionspace_2_create;
// static fenics_function_space_factory_ptr HyperElasticity_form_L_coefficientspace_T_create = HyperElasticity_form_L__functionspace_3_create;

 /* End coefficient typedefs */

/* Start high-level typedefs */
static const fenics_form_factory_ptr HyperElasticity_bilinearform_create = HyperElasticity_form_a_create;
static const fenics_form_factory_ptr HyperElasticity_linearform_create = HyperElasticity_form_L_create;

static const fenics_function_space_factory_ptr HyperElasticity_functionspace_create = HyperElasticity_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
