// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'uflacs',
//   'scalar_type': 'double',
//   'timeout': 10}


#pragma once

typedef double fenics_scalar_t;
#include <fenics_interface.h>

#ifdef __cplusplus
extern "C" {
#endif

fenics_finite_element* create_ffc_element_496dcc2f002f8bd29234476a4c8fa0a3efd63efb_finite_element_main(void);

fenics_finite_element* create_ffc_element_648437b5c7ff9a32325fb64e5193a33f44784fc1_finite_element_main(void);

fenics_finite_element* create_ffc_element_392bbf16c23ca3243a70e66e583db2c280b3601b_finite_element_main(void);

fenics_dofmap* create_ffc_element_496dcc2f002f8bd29234476a4c8fa0a3efd63efb_dofmap_main(void);

fenics_dofmap* create_ffc_element_648437b5c7ff9a32325fb64e5193a33f44784fc1_dofmap_main(void);

fenics_dofmap* create_ffc_element_392bbf16c23ca3243a70e66e583db2c280b3601b_dofmap_main(void);

fenics_coordinate_mapping* create_ffc_coordinate_mapping_3631f6fb40e874a885198dfcf74e60d36da645a2_coordinate_mapping_main(void);

fenics_integral* create_poissondg_cell_integral_e35f641731b0c974b4b7520e23d69f4f726a7b2d_otherwise(void);

fenics_integral* create_poissondg_exterior_facet_integral_e35f641731b0c974b4b7520e23d69f4f726a7b2d_otherwise(void);

fenics_integral* create_poissondg_interior_facet_integral_e35f641731b0c974b4b7520e23d69f4f726a7b2d_otherwise(void);

fenics_integral* create_poissondg_cell_integral_f74f75e56aa99140e8176029cc3cd69b6c21f0d1_otherwise(void);

fenics_integral* create_poissondg_exterior_facet_integral_f74f75e56aa99140e8176029cc3cd69b6c21f0d1_otherwise(void);

fenics_form* create_poissondg_form_e35f641731b0c974b4b7520e23d69f4f726a7b2d(void);

fenics_form* create_poissondg_form_f74f75e56aa99140e8176029cc3cd69b6c21f0d1(void);


// Typedefs for convenience pointers to functions (factories)
typedef fenics_function_space* (*fenics_function_space_factory_ptr)(void);
typedef fenics_form* (*fenics_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 2)
fenics_function_space* PoissonDG_coefficientspace_f_create(void);
fenics_function_space* PoissonDG_coefficientspace_gN_create(void);

// Form function spaces helpers (form 'a')
fenics_function_space* PoissonDG_form_a_functionspace_0_create(void);

fenics_function_space* PoissonDG_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
/*   - No form coefficients */
/*    Form helper */
static const fenics_form_factory_ptr PoissonDG_form_a_create = create_poissondg_form_e35f641731b0c974b4b7520e23d69f4f726a7b2d;

/*    Typedefs (function spaces for form_a) */
static const fenics_function_space_factory_ptr PoissonDG_form_a_testspace_create = PoissonDG_form_a_functionspace_0_create;
static const fenics_function_space_factory_ptr PoissonDG_form_a_trialspace_create = PoissonDG_form_a_functionspace_1_create;


 /* End coefficient typedefs */

// Form function spaces helpers (form 'L')
fenics_function_space* PoissonDG_form_L_functionspace_0_create(void);

/* Coefficient function space typedefs for form "form_L" */
static const fenics_function_space_factory_ptr PoissonDG_form_L_functionspace_1_create = PoissonDG_coefficientspace_f_create;
static const fenics_function_space_factory_ptr PoissonDG_form_L_functionspace_2_create = PoissonDG_coefficientspace_gN_create;
/*    Form helper */
static const fenics_form_factory_ptr PoissonDG_form_L_create = create_poissondg_form_f74f75e56aa99140e8176029cc3cd69b6c21f0d1;

/*    Typedefs (function spaces for form_L) */
static const fenics_function_space_factory_ptr PoissonDG_form_L_testspace_create = PoissonDG_form_L_functionspace_0_create;
// static fenics_function_space_factory_ptr PoissonDG_form_L_coefficientspace_f_create = PoissonDG_form_L__functionspace_1_create;
// static fenics_function_space_factory_ptr PoissonDG_form_L_coefficientspace_gN_create = PoissonDG_form_L__functionspace_2_create;

 /* End coefficient typedefs */

/* Start high-level typedefs */
static const fenics_form_factory_ptr PoissonDG_bilinearform_create = PoissonDG_form_a_create;
static const fenics_form_factory_ptr PoissonDG_linearform_create = PoissonDG_form_L_create;

static const fenics_function_space_factory_ptr PoissonDG_functionspace_create = PoissonDG_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
