// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'uflacs',
//   'scalar_type': 'double',
//   'timeout': 10}


typedef double fenics_scalar_t;
#include <fenics_interface.h>
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

// Code for element ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main

int value_dimension_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(int i)
{
  return 1;
}

int reference_value_dimension_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(int i)
{
  return 1;
}

int evaluate_reference_basis_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(double* restrict reference_values,
                                            int num_points,
                                            const double* restrict X)
{
  static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
for (int64_t k = 0; k < num_points * 3; ++k)
    reference_values[k] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Accumulate products of coefficients and basisvalues
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip + 1] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[3 * ip + 2] += coefficients2[0][r] * basisvalues1[r];
}
return 0;
}

int evaluate_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(double * restrict reference_values,
                                          int order, int num_points,
                                          const double * restrict X)
{
  if (order == 0)
    return evaluate_reference_basis_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(reference_values, num_points, X);
const int64_t num_derivatives = pow(2, order);
for (int64_t l0 = 0; l0 < num_points * 3 * num_derivatives; ++l0)
    reference_values[l0] = 0.0;
if (order > 1)
    return 0;
// Tables of derivatives of the polynomial base (transpose).
alignas(32) static const double dmats0[2][3][3] =
    { { { 0.0, 0.0, 0.0 },
        { 4.8989794855663495, 0.0, 0.0 },
        { 0.0, 0.0, 0.0 } },
      { { 0.0, 0.0, 0.0 },
        { 2.449489742783182, 0.0, 0.0 },
        { 4.242640687119285, 0.0, 0.0 } } };
static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
const int64_t reference_offset[3] = { 0 };
const int64_t num_components[3] = { 1, 1, 1 };
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Loop over all dofs
    for (int64_t i = 0; i < 3; ++i)
    {
        double derivatives[2] = { 0 };
        switch (i)
        {
        case 0:
            // Compute reference derivatives for dof 0.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 1:
            // Compute reference derivatives for dof 1.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 2:
            // Compute reference derivatives for dof 2.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        }
        for (int64_t r = 0; r < num_derivatives; ++r)
            for (int64_t c = 0; c < num_components[i]; ++c)
                reference_values[3 * num_derivatives * ip + num_derivatives * i + r + (reference_offset[i] + c)] = derivatives[num_derivatives * c + r];
    }
}
return 0;
}

int transform_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K,
    int cell_orientation)
{
  const int64_t num_derivatives = pow(2, order);
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t l = 0; l < num_points * 3 * num_derivatives; ++l)
    values[l] = 0.0;
const int64_t reference_offsets[3] = { 0 };
const int64_t physical_offsets[3] = { 0 };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    double transform[2][2];
    for (int64_t r = 0; r < num_derivatives; ++r)
        for (int64_t s = 0; s < num_derivatives; ++s)
            transform[r][s] = 1.0;
    for (int64_t r = 0; r < num_derivatives; ++r)
        for (int64_t s = 0; s < num_derivatives; ++s)
            for (int64_t k = 0; k < order; ++k)
                transform[r][s] *= K[2 * 2 * ip + 2 * combinations[order - 1][s][k] + combinations[order - 1][r][k]];
    for (int64_t d = 0; d < 3; ++d)
    {
        for (int64_t s = 0; s < num_derivatives; ++s)
        {
            for (int64_t i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[3 * num_derivatives * ip + num_derivatives * d + s + reference_offsets[d]];
                // Mapping derivatives back to the physical element
                for (int64_t r = 0; r < num_derivatives; ++r)
                    values[3 * num_derivatives * ip + num_derivatives * d + r + (physical_offsets[d] + i)] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}

int transform_values_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(
     fenics_scalar_t* restrict reference_values,
     const fenics_scalar_t* restrict physical_values,
     const double* restrict coordinate_dofs,
     int cell_orientation,
     const fenics_coordinate_mapping* cm)
{
  reference_values[0] = physical_values[0];
reference_values[1] = physical_values[1];
reference_values[2] = physical_values[2];
return 0;
}

int tabulate_reference_dof_coordinates_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(double* restrict reference_dof_coordinates)
{
  static const double dof_X[6] = { 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 };
memcpy(reference_dof_coordinates, dof_X, 6*sizeof(double));
return 0;
}


fenics_finite_element* create_sub_element_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(int i)
{
  return NULL;
}

fenics_finite_element* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(void)
{
  fenics_finite_element* element = malloc(sizeof(*element));

  element->signature = "FiniteElement('Lagrange', triangle, 1)";
  element->cell_shape = triangle;
  element->topological_dimension = 2;
  element->geometric_dimension = 2;
  element->space_dimension = 3;
  element->value_rank = 0;
  element->value_dimension = value_dimension_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->value_size = 1;
  element->reference_value_rank = 0;
  element->reference_value_dimension = reference_value_dimension_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->reference_value_size = 1;
  element->degree = 1;
  element->family = "Lagrange";
  element->evaluate_reference_basis = evaluate_reference_basis_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->evaluate_reference_basis_derivatives = evaluate_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->transform_values = transform_values_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->tabulate_reference_dof_coordinates = tabulate_reference_dof_coordinates_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->num_sub_elements = 0;
  element->create_sub_element = create_sub_element_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  element->create = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;

  return element;
};

// End of code for element ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main

// Code for element ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main

int value_dimension_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(int i)
{
  static const int return_values[1] = { 2 };
if (i >= 1)
    return 1;
return return_values[i];
}

int reference_value_dimension_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(int i)
{
  static const int return_values[1] = { 2 };
if (i >= 1)
    return 1;
return return_values[i];
}

int evaluate_reference_basis_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(double* restrict reference_values,
                                            int num_points,
                                            const double* restrict X)
{
  static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
for (int64_t k = 0; k < num_points * 6 * 2; ++k)
    reference_values[k] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Accumulate products of coefficients and basisvalues
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip + 2] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip + 2 * 2] += coefficients2[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip + 2 * 3 + 1] += coefficients0[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip + 2 * 4 + 1] += coefficients1[0][r] * basisvalues1[r];
    for (int64_t r = 0; r < 3; ++r)
        reference_values[6 * 2 * ip + 2 * 5 + 1] += coefficients2[0][r] * basisvalues1[r];
}
return 0;
}

int evaluate_reference_basis_derivatives_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(double * restrict reference_values,
                                          int order, int num_points,
                                          const double * restrict X)
{
  if (order == 0)
    return evaluate_reference_basis_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(reference_values, num_points, X);
const int64_t num_derivatives = pow(2, order);
for (int64_t l0 = 0; l0 < num_points * 6 * num_derivatives * 2; ++l0)
    reference_values[l0] = 0.0;
if (order > 1)
    return 0;
// Tables of derivatives of the polynomial base (transpose).
alignas(32) static const double dmats0[2][3][3] =
    { { { 0.0, 0.0, 0.0 },
        { 4.8989794855663495, 0.0, 0.0 },
        { 0.0, 0.0, 0.0 } },
      { { 0.0, 0.0, 0.0 },
        { 2.449489742783182, 0.0, 0.0 },
        { 4.242640687119285, 0.0, 0.0 } } };
static const double coefficients0[1][3] = { { 0.4714045207910317, -0.2886751345948129, -0.16666666666666666 } };
static const double coefficients1[1][3] = { { 0.4714045207910317, 0.2886751345948129, -0.16666666666666666 } };
static const double coefficients2[1][3] = { { 0.4714045207910316, 0.0, 0.3333333333333333 } };
const int64_t reference_offset[6] = { 0, 0, 0, 1, 1, 1 };
const int64_t num_components[6] = { 1, 1, 1, 1, 1, 1 };
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Map from UFC reference coordinate X to FIAT reference coordinate Y
    const double Y[2] = { 2.0 * X[ip * 2] - 1.0, 2.0 * X[ip * 2 + 1] - 1.0 };
    // Compute basisvalues for each relevant embedded degree
    double basisvalues1[3] = { 0 };
    basisvalues1[0] = 1.0;
    const double tmp1_1 = (1.0 + 2.0 * Y[0] + Y[1]) / 2.0;
    basisvalues1[1] = tmp1_1;
    basisvalues1[2] = (0.5 + 1.5 * Y[1]) * basisvalues1[0];
    basisvalues1[0] *= sqrt(0.5);
    basisvalues1[2] *= sqrt(1.0);
    basisvalues1[1] *= sqrt(3.0);
    // Loop over all dofs
    for (int64_t i = 0; i < 6; ++i)
    {
        double derivatives[2] = { 0 };
        switch (i)
        {
        case 0:
            // Compute reference derivatives for dof 0.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 1:
            // Compute reference derivatives for dof 1.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 2:
            // Compute reference derivatives for dof 2.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        case 3:
            // Compute reference derivatives for dof 3.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients0[0][s] * aux[s];
            }
            break;
        case 4:
            // Compute reference derivatives for dof 4.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients1[0][s] * aux[s];
            }
            break;
        case 5:
            // Compute reference derivatives for dof 5.
            for (int64_t r = 0; r < num_derivatives; ++r)
            {
                double aux[3] = { 0 };
                // Declare derivative matrix (of polynomial basis).
                double dmats[3][3] = {{ 0 }};
                // Initialize dmats.
                int64_t comb = combinations[order - 1][r][0];
                memcpy(&dmats[0][0], &dmats0[comb][0][0], 9*sizeof(double));
                // Looping derivative order to generate dmats.
                for (int64_t s = 1; s < order; ++s)
                {
                    // Store previous dmats matrix.
                    double dmats_old[3][3];
                    memcpy(&dmats_old[0][0], &dmats[0][0], 9*sizeof(double));
                    // Resetting dmats.
                    for (int64_t l0 = 0; l0 < 3; ++l0)
                        for (int64_t l1 = 0; l1 < 3; ++l1)
                            dmats[l0][l1] = 0.0;
                    // Update dmats using an inner product.
                    comb = combinations[order - 1][r][s];
                    for (int64_t t = 0; t < 3; ++t)
                        for (int64_t u = 0; u < 3; ++u)
                            for (int64_t tu = 0; tu < 3; ++tu)
                                dmats[t][u] += dmats0[comb][t][tu] * dmats_old[tu][u];
                }
                for (int64_t s = 0; s < 3; ++s)
                    for (int64_t t = 0; t < 3; ++t)
                        aux[s] += dmats[s][t] * basisvalues1[t];
                derivatives[r] = 0.0;
                for (int64_t s = 0; s < 3; ++s)
                    derivatives[r] += coefficients2[0][s] * aux[s];
            }
            break;
        }
        for (int64_t r = 0; r < num_derivatives; ++r)
            for (int64_t c = 0; c < num_components[i]; ++c)
                reference_values[6 * (num_derivatives * 2) * ip + num_derivatives * 2 * i + 2 * r + (reference_offset[i] + c)] = derivatives[num_derivatives * c + r];
    }
}
return 0;
}

int transform_reference_basis_derivatives_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(
    double * restrict values, int order, int num_points,
    const double * restrict reference_values,
    const double * restrict X, const double * restrict J,
    const double * restrict detJ, const double * restrict K,
    int cell_orientation)
{
  const int64_t num_derivatives = pow(2, order);
// Precomputed combinations
const int64_t combinations[1][2][1] =
    { { { 0 },
        { 1 } } };
for (int64_t l = 0; l < num_points * 6 * num_derivatives * 2; ++l)
    values[l] = 0.0;
const int64_t reference_offsets[6] = { 0, 0, 0, 1, 1, 1 };
const int64_t physical_offsets[6] = { 0, 0, 0, 1, 1, 1 };
for (int64_t ip = 0; ip < num_points; ++ip)
{
    double transform[2][2];
    for (int64_t r = 0; r < num_derivatives; ++r)
        for (int64_t s = 0; s < num_derivatives; ++s)
            transform[r][s] = 1.0;
    for (int64_t r = 0; r < num_derivatives; ++r)
        for (int64_t s = 0; s < num_derivatives; ++s)
            for (int64_t k = 0; k < order; ++k)
                transform[r][s] *= K[2 * 2 * ip + 2 * combinations[order - 1][s][k] + combinations[order - 1][r][k]];
    for (int64_t d = 0; d < 6; ++d)
    {
        for (int64_t s = 0; s < num_derivatives; ++s)
        {
            for (int64_t i = 0; i < 1; ++i)
            {
                // Using affine transform to map values back to the physical element.
                const double mapped_value = reference_values[6 * (num_derivatives * 2) * ip + num_derivatives * 2 * d + 2 * s + reference_offsets[d]];
                // Mapping derivatives back to the physical element
                for (int64_t r = 0; r < num_derivatives; ++r)
                    values[6 * (num_derivatives * 2) * ip + num_derivatives * 2 * d + 2 * r + (physical_offsets[d] + i)] += transform[r][s] * mapped_value;
            }
        }
    }
}
// Using affine transform to map values back to the physical element.
return 0;
}

int transform_values_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(
     fenics_scalar_t* restrict reference_values,
     const fenics_scalar_t* restrict physical_values,
     const double* restrict coordinate_dofs,
     int cell_orientation,
     const fenics_coordinate_mapping* cm)
{
  reference_values[0] = physical_values[0];
reference_values[1] = physical_values[2];
reference_values[2] = physical_values[4];
reference_values[3] = physical_values[7];
reference_values[4] = physical_values[9];
reference_values[5] = physical_values[11];
return 0;
}

int tabulate_reference_dof_coordinates_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(double* restrict reference_dof_coordinates)
{
  static const double dof_X[12] = { 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 };
memcpy(reference_dof_coordinates, dof_X, 12*sizeof(double));
return 0;
}

fenics_finite_element* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(void);

fenics_finite_element* create_sub_element_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(int i)
{
  switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
default:
    return NULL;
}
}

fenics_finite_element* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(void)
{
  fenics_finite_element* element = malloc(sizeof(*element));

  element->signature = "VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)";
  element->cell_shape = triangle;
  element->topological_dimension = 2;
  element->geometric_dimension = 2;
  element->space_dimension = 6;
  element->value_rank = 1;
  element->value_dimension = value_dimension_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->value_size = 2;
  element->reference_value_rank = 1;
  element->reference_value_dimension = reference_value_dimension_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->reference_value_size = 2;
  element->degree = 1;
  element->family = "Lagrange";
  element->evaluate_reference_basis = evaluate_reference_basis_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->evaluate_reference_basis_derivatives = evaluate_reference_basis_derivatives_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->transform_reference_basis_derivatives = transform_reference_basis_derivatives_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->transform_values = transform_values_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->tabulate_reference_dof_coordinates = tabulate_reference_dof_coordinates_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->num_sub_elements = 2;
  element->create_sub_element = create_sub_element_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;
  element->create = create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main;

  return element;
};

// End of code for element ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main

// Code for dofmap ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main

void tabulate_entity_dofs_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    }
    break;
}
}


fenics_dofmap* create_sub_dofmap_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(int i)
{
return NULL;
}

fenics_dofmap* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(void)
{
  fenics_dofmap* dofmap = malloc(sizeof(*dofmap));
  dofmap->signature = "FFC dofmap for FiniteElement('Lagrange', triangle, 1)";
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 3;
  dofmap->num_entity_dofs[0] = 1;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  dofmap->num_sub_dofmaps = 0;
  dofmap->create_sub_dofmap = create_sub_dofmap_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  dofmap->create = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;

  return dofmap;
};

// End of code for dofmap ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main

// Code for dofmap ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main

void tabulate_entity_dofs_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        dofs[1] = 3;
        break;
    case 1:
        dofs[0] = 1;
        dofs[1] = 4;
        break;
    case 2:
        dofs[0] = 2;
        dofs[1] = 5;
        break;
    }
    break;
}
}

fenics_dofmap* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(void);

fenics_dofmap* create_sub_dofmap_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
default:
    return NULL;
}
}

fenics_dofmap* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(void)
{
  fenics_dofmap* dofmap = malloc(sizeof(*dofmap));
  dofmap->signature = "FFC dofmap for VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)";
  dofmap->num_global_support_dofs = 0;
  dofmap->num_element_support_dofs = 6;
  dofmap->num_entity_dofs[0] = 2;
  dofmap->num_entity_dofs[1] = 0;
  dofmap->num_entity_dofs[2] = 0;
  dofmap->num_entity_dofs[3] = 0;
  dofmap->tabulate_entity_dofs = tabulate_entity_dofs_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main;
  dofmap->num_sub_dofmaps = 2;
  dofmap->create_sub_dofmap = create_sub_dofmap_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main;
  dofmap->create = create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main;

  return dofmap;
};

// End of code for dofmap ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main

// Code for coordinate mapping ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main

fenics_finite_element* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(void);

fenics_finite_element* create_coordinate_finite_element_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main();
}

fenics_dofmap* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(void);

fenics_dofmap* create_coordinate_dofmap_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main();
}


int evaluate_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(double* restrict reference_values,
    int order, int num_points, const double* restrict X);

void compute_jacobians_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict J, int num_points,
                                      const double* restrict X,
                                      const double* restrict coordinate_dofs)
{
double dphi[6];
for (int64_t l = 0; l < num_points * 2 * 2; ++l)
    J[l] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Compute basis derivatives of coordinate element
    evaluate_reference_basis_derivatives_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(dphi, 1, 1, &X[2 * ip]);
    // Compute J
    for (int64_t i = 0; i < 2; ++i)
        for (int64_t j = 0; j < 2; ++j)
            for (int64_t d = 0; d < 3; ++d)
                J[2 * 2 * ip + 2 * i + j] += coordinate_dofs[2 * d + i] * dphi[2 * d + j];
}
}

void compute_jacobian_determinants_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict detJ, int num_points,
                                                  const double* restrict J, int cell_orientation)
{
for (int64_t ip = 0; ip < num_points; ++ip)
    detJ[ip] = J[2 * 2 * ip] * J[2 * 2 * ip + 2 + 1] - J[2 * 2 * ip + 1] * J[2 * 2 * ip + 2];
}

void compute_jacobian_inverses_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict K, int num_points,
    const double* restrict J, const double* restrict detJ)
{
for (int64_t ip = 0; ip < num_points; ++ip)
{
    K[2 * 2 * ip] = J[2 * 2 * ip + 2 + 1] / detJ[ip];
    K[2 * 2 * ip + 1] = -J[2 * 2 * ip + 1] / detJ[ip];
    K[2 * 2 * ip + 2] = -J[2 * 2 * ip + 2] / detJ[ip];
    K[2 * 2 * ip + 2 + 1] = J[2 * 2 * ip] / detJ[ip];
}
}


int evaluate_reference_basis_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(double* restrict reference_values,
    int num_points, const double* restrict X);

void compute_physical_coordinates_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict x, int num_points,
                                                 const double* restrict X,
                                                 const double* restrict coordinate_dofs)
{
double phi[3];
for (int64_t i = 0; i < num_points * 2; ++i)
    x[i] = 0.0;
for (int64_t ip = 0; ip < num_points; ++ip)
{
    // Compute basis values of coordinate element
    evaluate_reference_basis_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(phi, 1, &X[2 * ip]);
    // Compute x
    for (int64_t i = 0; i < 2; ++i)
        for (int64_t d = 0; d < 3; ++d)
            x[2 * ip + i] += coordinate_dofs[2 * d + i] * phi[d];
}
}

void compute_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict x, double* restrict J,
                                     double* restrict detJ, double* restrict K,
                                     int num_points, const double* restrict X,
                                     const double* restrict coordinate_dofs,
                                     int cell_orientation)
{
compute_physical_coordinates_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(x, num_points, X, coordinate_dofs);
compute_jacobians_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(J, num_points, X, coordinate_dofs);
compute_jacobian_determinants_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(detJ, num_points, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(K, num_points, J, detJ);
}

void compute_midpoint_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict x, double* restrict J,
                                              const double* restrict coordinate_dofs)
{
const double phi_Xm[3] = { 0.33333333333333337, 0.33333333333333337, 0.3333333333333333 };
const double dphi_Xm[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
for (int64_t l = 0; l < 4; ++l)
    J[l] = 0.0;
// Compute x
for (int64_t i = 0; i < 2; ++i)
{
    x[i] = 0.0;
    for (int64_t d = 0; d < 3; ++d)
        x[i] += coordinate_dofs[2 * d + i] * phi_Xm[d];
}
// Compute J
for (int64_t i = 0; i < 2; ++i)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t d = 0; d < 3; ++d)
            J[2 * i + j] += coordinate_dofs[2 * d + i] * dphi_Xm[j][d];
}

void compute_reference_coordinates_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict X, int num_points,
                                                  const double* restrict x,
                                                  const double* restrict coordinate_dofs,
                                                  int cell_orientation)
{
for (int64_t l = 0; l < num_points * 2; ++l)
    X[l] = 0.0;
const double phi_X0[3] = { 1.0, 0.0, 0.0 };
const double dphi_X0[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
double J[4];
double detJ[1];
double K[4];
double x0[2] = { 0 };
for (int64_t i = 0; i < 2; ++i)
    for (int64_t k = 0; k < 3; ++k)
        x0[i] += coordinate_dofs[2 * k + i] * phi_X0[k];
for (int64_t i = 0; i < 2; ++i)
{
    for (int64_t j = 0; j < 2; ++j)
    {
        J[2 * i + j] = 0.0;
        for (int64_t k = 0; k < 3; ++k)
            J[2 * i + j] += coordinate_dofs[2 * k + i] * dphi_X0[j][k];
    }
}
compute_jacobian_determinants_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(detJ, 1, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(K, 1, J, detJ);
for (int64_t ip = 0; ip < num_points; ++ip)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t i = 0; i < 2; ++i)
            X[2 * ip + j] += K[2 * j + i] * (x[2 * ip + i] - x0[i]);
}

void compute_reference_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(double* restrict X, double* restrict J,
                                               double* restrict detJ, double* restrict K,
                                               int num_points, const double* restrict x,
                                               const double* restrict coordinate_dofs,
                                               int cell_orientation)
{
for (int64_t l = 0; l < num_points * 2; ++l)
    X[l] = 0.0;
const double phi_X0[3] = { 1.0, 0.0, 0.0 };
const double dphi_X0[2][3] =
    { { -1.0, 1.0, 0.0 },
      { -1.0, 0.0, 1.0 } };
double x0[2] = { 0 };
for (int64_t i = 0; i < 2; ++i)
    for (int64_t k = 0; k < 3; ++k)
        x0[i] += coordinate_dofs[2 * k + i] * phi_X0[k];
for (int64_t i = 0; i < 2; ++i)
{
    for (int64_t j = 0; j < 2; ++j)
    {
        J[2 * i + j] = 0.0;
        for (int64_t k = 0; k < 3; ++k)
            J[2 * i + j] += coordinate_dofs[2 * k + i] * dphi_X0[j][k];
    }
}
compute_jacobian_determinants_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(detJ, 1, J, cell_orientation);
compute_jacobian_inverses_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(K, 1, J, detJ);
for (int64_t ip = 0; ip < num_points; ++ip)
    for (int64_t j = 0; j < 2; ++j)
        for (int64_t i = 0; i < 2; ++i)
            X[2 * ip + j] += K[2 * j + i] * (x[2 * ip + i] - x0[i]);
}




fenics_coordinate_mapping* create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(void)
{
  fenics_coordinate_mapping* cmap = malloc(sizeof(*cmap));
  cmap->signature = "FFC coordinate_mapping from VectorElement(FiniteElement('Lagrange', triangle, 1), dim=2)";
  cmap->create = create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->geometric_dimension = 2;
  cmap->topological_dimension = 2;
  cmap->cell_shape = triangle;
  cmap->create_coordinate_finite_element = create_coordinate_finite_element_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->create_coordinate_dofmap = create_coordinate_dofmap_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_physical_coordinates = compute_physical_coordinates_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_reference_coordinates = compute_reference_coordinates_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_reference_geometry = compute_reference_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_jacobians = compute_jacobians_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_jacobian_determinants = compute_jacobian_determinants_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_jacobian_inverses = compute_jacobian_inverses_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_geometry = compute_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  cmap->compute_midpoint_geometry = compute_midpoint_geometry_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  return cmap;
}

// End of code for coordinate mapping ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main

// Code for integral poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise


void tabulate_tensor_poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise(fenics_scalar_t* restrict A, const fenics_scalar_t* w,
                                    const fenics_scalar_t* c,
                                    const double* restrict coordinate_dofs,
                                    const int* unused_local_index,
                                    const int* cell_orientation)
{
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const fenics_scalar_t FE3_C0_D01_Q1[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    const double J_c0 = coordinate_dofs[0] * FE3_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE3_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE3_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE3_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE3_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE3_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE3_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE3_C0_D01_Q1[0][0][1];
    alignas(32) fenics_scalar_t sp[30];
    sp[0] = c[0] * c[4];
    sp[1] = c[2] * c[6];
    sp[2] = sp[0] + sp[1];
    sp[3] = c[1] * c[5];
    sp[4] = c[3] * c[7];
    sp[5] = sp[3] + sp[4];
    sp[6] = sp[2] + sp[5];
    sp[7] = J_c0 * J_c3;
    sp[8] = J_c1 * J_c2;
    sp[9] = sp[7] + -1 * sp[8];
    sp[10] = J_c0 / sp[9];
    sp[11] = -1 * J_c1 / sp[9];
    sp[12] = sp[10] * sp[10];
    sp[13] = sp[10] * sp[11];
    sp[14] = sp[11] * sp[11];
    sp[15] = J_c3 / sp[9];
    sp[16] = -1 * J_c2 / sp[9];
    sp[17] = sp[16] * sp[16];
    sp[18] = sp[15] * sp[16];
    sp[19] = sp[15] * sp[15];
    sp[20] = sp[12] + sp[17];
    sp[21] = sp[13] + sp[18];
    sp[22] = sp[19] + sp[14];
    sp[23] = sp[6] * sp[20];
    sp[24] = sp[6] * sp[21];
    sp[25] = sp[6] * sp[22];
    sp[26] = fabs(sp[9]);
    sp[27] = sp[23] * sp[26];
    sp[28] = sp[24] * sp[26];
    sp[29] = sp[25] * sp[26];
    // UFLACS block mode: preintegrated
    A[0] += 0.5 * sp[29] + 0.5 * sp[28] + 0.5 * sp[28] + 0.5 * sp[27];
    A[1] += -0.5 * sp[29] + -0.5 * sp[28];
    A[2] += -0.5 * sp[28] + -0.5 * sp[27];
    A[3] += -0.5 * sp[29] + -0.5 * sp[28];
    A[4] += 0.5 * sp[29];
    A[5] += 0.5 * sp[28];
    A[6] += -0.5 * sp[28] + -0.5 * sp[27];
    A[7] += 0.5 * sp[28];
    A[8] += 0.5 * sp[27];
}


fenics_integral* create_poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise(void)
{
  static const bool enabled[] = {};

  fenics_integral* integral = malloc(sizeof(*integral));
  integral->enabled_coefficients = enabled;
  integral->tabulate_tensor = tabulate_tensor_poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise;
  return integral;
};

// End of code for integral poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise

// Code for integral poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise


void tabulate_tensor_poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise(fenics_scalar_t* restrict A, const fenics_scalar_t* w,
                                    const fenics_scalar_t* c,
                                    const double* restrict coordinate_dofs,
                                    const int* unused_local_index,
                                    const int* cell_orientation)
{
    // Quadrature rules
    alignas(32) static const fenics_scalar_t weights3[3] = { 0.1666666666666667, 0.1666666666666667, 0.1666666666666667 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const fenics_scalar_t FE3_C0_Q3[1][3][3] =
        { { { 0.6666666666666669, 0.1666666666666666, 0.1666666666666667 },
            { 0.1666666666666667, 0.1666666666666666, 0.6666666666666665 },
            { 0.1666666666666667, 0.6666666666666665, 0.1666666666666666 } } };
    alignas(32) static const fenics_scalar_t FE4_C0_D01_Q3[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    const double J_c0 = coordinate_dofs[0] * FE4_C0_D01_Q3[0][0][0] + coordinate_dofs[2] * FE4_C0_D01_Q3[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE4_C0_D01_Q3[0][0][0] + coordinate_dofs[5] * FE4_C0_D01_Q3[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE4_C0_D01_Q3[0][0][0] + coordinate_dofs[4] * FE4_C0_D01_Q3[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE4_C0_D01_Q3[0][0][0] + coordinate_dofs[3] * FE4_C0_D01_Q3[0][0][1];
    alignas(32) fenics_scalar_t sp[4];
    sp[0] = J_c0 * J_c3;
    sp[1] = J_c1 * J_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = fabs(sp[2]);
    // UFLACS block mode: full
    alignas(32) fenics_scalar_t BF0[3] = { 0 };
    for (int iq = 0; iq < 3; ++iq)
    {
        // Quadrature loop body setup (num_points=3)
        // Unstructured varying computations for num_points=3
        fenics_scalar_t w0 = 0.0;
        for (int ic = 0; ic < 3; ++ic)
            w0 += w[ic] * FE3_C0_Q3[0][iq][ic];
        alignas(32) fenics_scalar_t sv3[1];
        sv3[0] = sp[3] * w0;
        // UFLACS block mode: full
        const fenics_scalar_t fw0 = sv3[0] * weights3[iq];
        for (int i = 0; i < 3; ++i)
            BF0[i] += fw0 * FE3_C0_Q3[0][iq][i];
    }
    for (int i = 0; i < 3; ++i)
        A[i] += BF0[i];
}


fenics_integral* create_poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise(void)
{
  static const bool enabled[1] = { true };

  fenics_integral* integral = malloc(sizeof(*integral));
  integral->enabled_coefficients = enabled;
  integral->tabulate_tensor = tabulate_tensor_poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise;
  return integral;
};

// End of code for integral poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise

// Code for form poisson_form_d8593001c84542f37ff71d2959d153161d04f446

int original_coefficient_position_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int i)
{
// Invalid original coefficient index.
return -1;
}

// Return a list of the coefficient names.
const char** coefficient_name_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
static const char* names[2] = { "kappa1", "kappa2" };
return names;
}

fenics_finite_element* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(void);

fenics_finite_element* create_coordinate_finite_element_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main();
}

fenics_dofmap* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(void);

fenics_dofmap* create_coordinate_dofmap_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main();
}

fenics_coordinate_mapping* create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(void);

fenics_coordinate_mapping* create_coordinate_mapping_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
return create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main();
}

fenics_finite_element* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(void);

fenics_finite_element* create_finite_element_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
default:
    return NULL;
}
}

fenics_dofmap* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(void);

fenics_dofmap* create_dofmap_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
default:
    return NULL;
}
}

fenics_integral* create_cell_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int subdomain_id)
{
  switch (subdomain_id)
{
case -1:
    return create_poisson_cell_integral_d8593001c84542f37ff71d2959d153161d04f446_otherwise();
default:
    return NULL;
}
}

void get_cell_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int *ids)
{
  ids[0] = -1;
return;
}

fenics_integral* create_exterior_facet_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int subdomain_id)
{
  return NULL;
}

void get_exterior_facet_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int *ids)
{
  return;
}

fenics_integral* create_interior_facet_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int subdomain_id)
{
return NULL;
}

void get_interior_facet_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int *ids)
{
  return;
}

fenics_integral* create_vertex_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int subdomain_id)
{
return NULL;
}

void get_vertex_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int *ids)
{
  return;
}

fenics_custom_integral* create_custom_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int subdomain_id)
{
return NULL;
}

void get_custom_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(int *ids)
{
  return;
}

fenics_form* create_poisson_form_d8593001c84542f37ff71d2959d153161d04f446(void)
{
  fenics_form* form = malloc(sizeof(*form));

  form->signature = "34b900fbd66abb832e0c8ee0ed3ddd86efa7b823e04bbd9a1e493e05e422ec3c608525c80e358316843aa41748e28c02dfbb7e5c11379dc910837e429b0ba0d3";
  form->rank = 2;
  form->num_coefficients = 0;
  form->num_constants = 2;
  form->original_coefficient_position = original_coefficient_position_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;

  form->coefficient_name_map = coefficient_name_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->constant_name_map = constant_name_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;

  form->create_coordinate_finite_element = create_coordinate_finite_element_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_coordinate_dofmap = create_coordinate_dofmap_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_coordinate_mapping = create_coordinate_mapping_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_finite_element = create_finite_element_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_dofmap = create_dofmap_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;

  form->get_cell_integral_ids = get_cell_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->get_exterior_facet_integral_ids = get_exterior_facet_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->get_interior_facet_integral_ids = get_interior_facet_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->get_vertex_integral_ids = get_vertex_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->get_custom_integral_ids = get_custom_integral_ids_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;

  form->num_cell_integrals = 1;
  form->num_exterior_facet_integrals = 0;
  form->num_interior_facet_integrals = 0;
  form->num_vertex_integrals = 0;
  form->num_custom_integrals = 0;

  form->create_cell_integral = create_cell_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_exterior_facet_integral = create_exterior_facet_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_interior_facet_integral = create_interior_facet_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_vertex_integral = create_vertex_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;
  form->create_custom_integral = create_custom_integral_poisson_form_d8593001c84542f37ff71d2959d153161d04f446;

  return form;
};

// End of code for form poisson_form_d8593001c84542f37ff71d2959d153161d04f446

// Code for form poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac

int original_coefficient_position_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int i)
{
if (i >= 1)
{
    // Invalid original coefficient index.
    return -1;
}
static const int64_t position[1] = { 0 };
return position[i];
}

// Return a list of the coefficient names.
const char** coefficient_name_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
static const char* names[1] = { "f" };
return names;
}

// Return a list of the constant names.
const char** constant_name_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
return NULL;
}

fenics_finite_element* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main(void);

fenics_finite_element* create_coordinate_finite_element_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_finite_element_main();
}

fenics_dofmap* create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main(void);

fenics_dofmap* create_coordinate_dofmap_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
return create_ffc_element_b11a58934c915d725294100980c2c544c341a2b3_dofmap_main();
}

fenics_coordinate_mapping* create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main(void);

fenics_coordinate_mapping* create_coordinate_mapping_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
return create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main();
}

fenics_finite_element* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main(void);

fenics_finite_element* create_finite_element_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main();
default:
    return NULL;
}
}

fenics_dofmap* create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main(void);

fenics_dofmap* create_dofmap_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int i)
{
switch (i)
{
case 0:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
case 1:
    return create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main();
default:
    return NULL;
}
}

fenics_integral* create_cell_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int subdomain_id)
{
  switch (subdomain_id)
{
case -1:
    return create_poisson_cell_integral_35b69c9edf900054c821da274ffb83fd2bdd3dac_otherwise();
default:
    return NULL;
}
}

void get_cell_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int *ids)
{
  ids[0] = -1;
return;
}

fenics_integral* create_exterior_facet_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int subdomain_id)
{
  return NULL;
}

void get_exterior_facet_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int *ids)
{
  return;
}

fenics_integral* create_interior_facet_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int subdomain_id)
{
return NULL;
}

void get_interior_facet_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int *ids)
{
  return;
}

fenics_integral* create_vertex_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int subdomain_id)
{
return NULL;
}

void get_vertex_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int *ids)
{
  return;
}

fenics_custom_integral* create_custom_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int subdomain_id)
{
return NULL;
}

void get_custom_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(int *ids)
{
  return;
}

fenics_form* create_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac(void)
{
  fenics_form* form = malloc(sizeof(*form));

  form->signature = "bf93b9e7946662352ff0f5a55dbd693fb23b2f0d8f258ce3d666b3a1f88d132be3b9c88ab2af518c4c3e8e7c2e7e81856f494aca0dfd44ec789c9c099616fbfd";
  form->rank = 1;
  form->num_coefficients = 1;
  form->num_constants = 0;
  form->original_coefficient_position = original_coefficient_position_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;

  form->coefficient_name_map = coefficient_name_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->constant_name_map = constant_name_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;

  form->create_coordinate_finite_element = create_coordinate_finite_element_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_coordinate_dofmap = create_coordinate_dofmap_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_coordinate_mapping = create_coordinate_mapping_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_finite_element = create_finite_element_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_dofmap = create_dofmap_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;

  form->get_cell_integral_ids = get_cell_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->get_exterior_facet_integral_ids = get_exterior_facet_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->get_interior_facet_integral_ids = get_interior_facet_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->get_vertex_integral_ids = get_vertex_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->get_custom_integral_ids = get_custom_integral_ids_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;

  form->num_cell_integrals = 1;
  form->num_exterior_facet_integrals = 0;
  form->num_interior_facet_integrals = 0;
  form->num_vertex_integrals = 0;
  form->num_custom_integrals = 0;

  form->create_cell_integral = create_cell_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_exterior_facet_integral = create_exterior_facet_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_interior_facet_integral = create_interior_facet_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_vertex_integral = create_vertex_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;
  form->create_custom_integral = create_custom_integral_poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac;

  return form;
};

// End of code for form poisson_form_35b69c9edf900054c821da274ffb83fd2bdd3dac

fenics_function_space* Poisson_coefficientspace_f_create(void)
{
  fenics_function_space* space = (fenics_function_space*) malloc(sizeof(*space));
  space->create_element = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  space->create_dofmap = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  space->create_coordinate_mapping = create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  return space;
}
fenics_function_space* Poisson_form_a_functionspace_0_create(void)
{
  fenics_function_space* space = (fenics_function_space*) malloc(sizeof(*space));
  space->create_element = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  space->create_dofmap = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  space->create_coordinate_mapping = create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  return space;
}

fenics_function_space* Poisson_form_a_functionspace_1_create(void)
{
  fenics_function_space* space = (fenics_function_space*) malloc(sizeof(*space));
  space->create_element = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  space->create_dofmap = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  space->create_coordinate_mapping = create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  return space;
}
fenics_function_space* Poisson_form_L_functionspace_0_create(void)
{
  fenics_function_space* space = (fenics_function_space*) malloc(sizeof(*space));
  space->create_element = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_finite_element_main;
  space->create_dofmap = create_ffc_element_c23891ce0fff60a57b0e177935a4dea989ffac04_dofmap_main;
  space->create_coordinate_mapping = create_ffc_coordinate_mapping_06741112b42e987b9f2e352fd932fb6913078154_coordinate_mapping_main;
  return space;
}

