// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFC version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'epsilon': 1e-14,
//   'external_include_dirs': '',
//   'external_includes': '',
//   'precision': None,
//   'quadrature_degree': None,
//   'quadrature_rule': None,
//   'representation': 'uflacs',
//   'scalar_type': 'double',
//   'timeout': 10}


#pragma once

typedef double fenics_scalar_t;
#include <fenics_interface.h>

#ifdef __cplusplus
extern "C" {
#endif

fenics_finite_element* create_ffc_element_556dc4ff78e840848979501108205ab346600e81_finite_element_main(void);

fenics_finite_element* create_ffc_element_c3e3c45678519c2aa0053b99814075cc54b47f9a_finite_element_main(void);

fenics_finite_element* create_ffc_element_ec01880a1aa40a92af0c6d54cb9e0435c0ed5008_finite_element_main(void);

fenics_dofmap* create_ffc_element_556dc4ff78e840848979501108205ab346600e81_dofmap_main(void);

fenics_dofmap* create_ffc_element_c3e3c45678519c2aa0053b99814075cc54b47f9a_dofmap_main(void);

fenics_dofmap* create_ffc_element_ec01880a1aa40a92af0c6d54cb9e0435c0ed5008_dofmap_main(void);

fenics_coordinate_mapping* create_ffc_coordinate_mapping_b228c09025d9fa35edb2f7dcd706142e113b68d7_coordinate_mapping_main(void);

fenics_integral* create_symmetry_cell_integral_5e2ad5a1b370c1d859e78ee36dc529ce3d58e799_otherwise(void);

fenics_form* create_symmetry_form_5e2ad5a1b370c1d859e78ee36dc529ce3d58e799(void);


// Typedefs for convenience pointers to functions (factories)
typedef fenics_function_space* (*fenics_function_space_factory_ptr)(void);
typedef fenics_form* (*fenics_form_factory_ptr)(void);

// Coefficient spaces helpers (number: 0)

// Form function spaces helpers (form 'a')
fenics_function_space* Symmetry_form_a_functionspace_0_create(void);

fenics_function_space* Symmetry_form_a_functionspace_1_create(void);

/* Coefficient function space typedefs for form "form_a" */
/*   - No form coefficients */
/*    Form helper */
static const fenics_form_factory_ptr Symmetry_form_a_create = create_symmetry_form_5e2ad5a1b370c1d859e78ee36dc529ce3d58e799;

/*    Typedefs (function spaces for form_a) */
static const fenics_function_space_factory_ptr Symmetry_form_a_testspace_create = Symmetry_form_a_functionspace_0_create;
static const fenics_function_space_factory_ptr Symmetry_form_a_trialspace_create = Symmetry_form_a_functionspace_1_create;


 /* End coefficient typedefs */

/* Start high-level typedefs */
static const fenics_form_factory_ptr Symmetry_bilinearform_create = Symmetry_form_a_create;

static const fenics_function_space_factory_ptr Symmetry_functionspace_create = Symmetry_form_a_functionspace_0_create;
/* End high-level typedefs */


#ifdef __cplusplus
}
#endif
