// Declare which classes should be stored using shared_ptr
%shared_ptr(ufc::dofmap)
%shared_ptr(ufc::finite_element)
%shared_ptr(ufc::function)
%shared_ptr(ufc::integral)
%shared_ptr(ufc::cell_integral)
%shared_ptr(ufc::exterior_facet_integral)
%shared_ptr(ufc::interior_facet_integral)
%shared_ptr(ufc::vertex_integral)
%shared_ptr(ufc::custom_integral)
%shared_ptr(ufc::cutcell_integral)
%shared_ptr(ufc::interface_integral)
%shared_ptr(ufc::overlap_integral)
%shared_ptr(ufc::form)
