[mypy]
# Suggested at https://blog.wolt.com/engineering/2021/09/30/professional-grade-mypy-configuration/
# Goal would be to make all of the below True long-term
disallow_untyped_defs = False
disallow_any_unimported = False
no_implicit_optional = False
check_untyped_defs = False
warn_return_any = False
warn_unused_ignores = False
show_error_codes = True

[mypy-pygraphviz.*]
ignore_missing_imports = True
[mypy-ufl.*]
ignore_missing_imports = True
[mypy-basix.*]
ignore_missing_imports = True
[mypy-cffi.*]
ignore_missing_imports = True
