#!/bin/bash
#
# Copyright (C) 2013 Anders Logg
#
# This file is part of FFC.
#
# FFC is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FFC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FFC. If not, see <http://www.gnu.org/licenses/>.
#
# Modified by Johannes Ring, 2013-04-23
#
# First added:  2013-04-22
# Last changed: 2013-06-24
#
# This script downloads the reference data for the FFC regression tests.

# Parameters
DATA_REPO="https://bitbucket.org/fenics-project/ffc-reference-data.git"
DATA_DIR="ffc-reference-data"

# Find first = latest reference data for current branch
HEAD=`git rev-list --max-count 1 HEAD`
echo "Looking for reference data ancestor of $HEAD"
REVS=`git rev-list HEAD`
REFS=`cd ffc-reference-data && ls | grep ffc-reference-data-`
TAG=`python compute_tag.py $REVS $REFS`
if [ "$TAG" = "none" ]; then
    echo "Unable to find reference data ancestor"
    exit 1
else
    echo "Found reference data: $TAG"
fi

# Get reference repository
if [ ! -d $DATA_DIR ]; then
    echo "Cloning reference data repository"
    git clone $DATA_REPO
else
    echo "Found existing reference data repository, pulling new data"
    (cd $DATA_DIR && git pull)
fi

# Make symbolic link to current references
echo ""
echo "Making symbolic link to current reference data:"
echo ""
echo "       $DATA_DIR/current"
echo "   --> $DATA_DIR/$TAG"
echo ""
(cd $DATA_DIR && rm -f current && ln -s $TAG current)
