"Code generation for the UFC 1.0 format."

__author__ = "Anders Logg (logg@simula.no)"
__date__ = "2007-01-08 -- 2007-01-08"
__copyright__ = "Copyright (C) 2007 Anders Logg"
__license__  = "GNU GPL Version 2"

# FFC common modules
from ffc.common.util import *
from ffc.common.debug import *
from ffc.common.constants import *

# FFC format modules
from ufc import *

# Specify formatting for code generation
format = { "sum": lambda l: " + ".join(l),
           "subtract": lambda l: " - ".join(l),
           "multiplication": lambda l: "*".join(l),
           "grouping": lambda s: "(%s)" % s,
           "determinant": "det",
           "floating point": lambda a: "%.15e" % a,
           "constant": lambda j: "c%d" % j,
           "coefficient table": lambda j, k: "c[%d][%d]" % (j, k),
           "coefficient": lambda j, k: "c%d_%d" % (j, k),
           "transform": lambda j, k, r: "%s.g%d%d" % (r, j, k),
           "reference tensor" : lambda j, i, a: None,
           "geometry tensor": lambda j, a: "G%d_%s" % (j, "_".join(["%d" % index for index in a])),
           "element tensor": lambda i, k: "block[%d]" % k,
           "tmp declaration": lambda j, k: "const real tmp%d_%d" % (j, k),
           "tmp access": lambda j, k: "tmp%d_%d" % (j, k) }

def init(options):
    "Initialize code generation for the UFC 1.0 format."
    pass
    
def write(forms, options):
    "Generate code for the UFC 1.0 format."
    debug("Generating code for UFC 1.0")

    for form in forms:
    
        # Get name of form
        name = form.name

        prefix = form.name.lower()

        # Generate file header
        output = ""
        output += __generate_header(name, options)

        # Generate code for ufc::finite_element(s)
        for i in range(len(form.finite_elements)):
            output += __generate_finite_element(form.finite_elements[i], prefix, i, options)

        # Generate code for ufc::form
        output += "\n"
        output += __generate_form(form, options)
    
        # Generate code for footer
        output += "\n"
        output += __generate_footer(name, options)

        # Write file
        filename = name + ".h"
        file = open(filename, "w")
        file.write(output)
        file.close()
        debug("Output written to " + filename)

def __generate_header(name, options):
    "Generate file header"

    # Check if BLAS is required
    if options["blas"]:
        blas_include = "\n#include <cblas.h>"
        blas_warning = "\n// Warning: This code was generated with '-f blas' and requires cblas.h."
    else:
        blas_include = ""
        blas_warning = ""
        
    return """\
// This code conforms with the UFC specification version 1.0.
//
// This code was automatically generated by FFC version %s.%s

#ifndef __%s_H
#define __%s_H

#include <ufc.h>%s
""" % (FFC_VERSION, blas_warning, name.upper(), name.upper(), blas_include)

def __generate_footer(name, options):
    "Generate file footer"
    return """\
#endif
"""

def __generate_dof_map(form, options):
    "Generate code for ufc::dof_map"
    
    code = {}
    code["classname"] = form.name
    code["members"] = ""
    code["constructor"] = "// Not implemented"
    code["destructor"] = "// Not implemented"
    code["signature"] = "// Not implemented"
    code["needs_mesh_entities"] = "// Not implemented"
    code["init_mesh"] = "// Not implemented"
    code["init_cell"] = "// Not implemented"
    code["global_dimension"] = "// Not implemented"
    code["local_dimension"] = "// Not implemented"
    code["num_facet_dofs"] = "// Not implemented"
    code["tabulate_dofs"] = "// Not implemented"
    code["tabulate_facet_dofs"] = "// Not implemented"

    return __generate_code(dof_map_combined, code)

def __generate_finite_element(element, prefix, i, options):
    "Generate code for ufc::finite_element"

    code = {}

    # Set class name
    code["classname"] = "%s_finite_element_%d" % (prefix, i)

    # Generate code for members
    code["members"] = ""

    # Generate code for constructor
    code["constructor"] = "// Do nothing"

    # Generate code for destructor
    code["destructor"] = "// Do nothing"

    
    code["signature"] = "// Not implemented"
    code["cell_shape"] = "// Not implemented"
    code["space_dimension"] = "// Not implemented"
    code["value_rank"] = "// Not implemented"
    code["value_dimension"] = "// Not implemented"
    code["evaluate_basis"] = "// Not implemented"
    code["evaluate_dof"] = "// Not implemented"
    code["interpolate_vertex_values"] = "// Not implemented"
    code["num_sub_elements"] = "// Not implemented"
    code["sub_element"] = "// Not implemented"

    return __generate_code(finite_element_combined, code)

def __generate_cell_integral(form, options):
    "Generate code for ufc::cell_integral"

    code = {}
    code["classname"] = form.name
    code["members"] = ""
    code["constructor"] = "// Not implemented"
    code["destructor"] = "// Not implemented"
    code["tabulate_tensor"] = "// Not implemented"
    
    return __generate_code(cell_integral_combined, code)

def __generate_exterior_facet_integral(form, options):
    "Generate code for ufc::exterior_facet_integral"

    code = {}
    code["classname"] = form.name
    code["members"] = ""
    code["constructor"] = "// Not implemented"
    code["destructor"] = "// Not implemented"
    code["tabulate_tensor"] = "// Not implemented"
    
    return __generate_code(exterior_facet_integral_combined, code)

def __generate_interior_facet_integral(form, options):
    "Generate code for ufc::interior_facet_integral"

    code = {}
    code["classname"] = form.name
    code["members"] = ""
    code["constructor"] = "// Not implemented"
    code["destructor"] = "// Not implemented"
    code["tabulate_tensor"] = "// Not implemented"
    
    return __generate_code(interior_facet_integral_combined, code)

def __generate_form(form, options):
    "Generate code for ufc::form"

    output = ""
    output += __generate_dof_map(form, options)

    output += __generate_cell_integral(form, options)
    output += __generate_exterior_facet_integral(form, options)
    output += __generate_interior_facet_integral(form, options)

    prefix = form.name.lower()
    code = {}

    # Set class name
    code["classname"] = prefix

    # Generate code for members
    code["members"] = ""

    # Generate code for constructor
    code["constructor"] = "// Do nothing"

    # Generate code for destructor
    code["destructor"] = "// Do nothing"

    # Generate code for signature
    code["signature"] = "return \"%s\";" % form.signature

    # Generate code for rank
    code["rank"] = "return %d;" % form.rank

    # Generate code for num_coefficients
    code["num_coefficients"] = "return %d;" % form.num_coefficients

    # Generate code for create_dof_map
    num_arguments = form.rank + form.num_coefficients
    body = "switch ( i )\n{\n"
    for i in range(num_arguments):
        body += "case %d:\n  return new %s_dof_map_%d();\n  break;\n" % (i, prefix, i)
    body += "default:\n  return 0;\n}"
    code["create_dof_map"] = body

    # Generate code for create_finite_element
    num_arguments = form.rank + form.num_coefficients
    body = "switch ( i )\n{\n"
    for i in range(num_arguments):
        body += "case %d:\n  return new %s_finite_element_%d();\n  break;\n" % (i, prefix, i)
    body += "default:\n  return 0;\n}"
    code["create_finite_element"] = body

    # Generate code for cell_integral
    code["create_cell_integral"] = "// Not implemented"

    # Generate code for exterior_facet_integral
    code["create_exterior_facet_integral"] = "// Not implemented"

    # Generate code for interior_facet_integral
    code["create_interior_facet_integral"] = "// Not implemented"

    output += __generate_code(form_combined, code)

    return output

def __generate_code(format_string, code):
    "Generate code according to format string and code dictionary"
    # Fix indentation
    for key in code:
        if not key in ["classname", "members"]:
            code[key] = indent(code[key], 4)
    # Generate code
    return format_string % code
