#!/bin/bash
#
# Copyright (C) 2013 Anders Logg
#
# This file is part of FFC.
#
# FFC is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FFC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FFC. If not, see <http://www.gnu.org/licenses/>.
#
# Modified by Johannes Ring, 2013-04-23
# Modified by Martin Sandve Alnaes, 2013-08-20
#
# First added:  2013-04-22
# Last changed: 2013-08-20
#
# This script downloads the reference data for the FFC regression tests.

# Parameters
source ./scripts/parameters

# Get reference repository
if [ ! -d $DATA_DIR ]; then
    echo "Cloning reference data repository"
    git clone $DATA_REPO
else
    echo "Found existing reference data repository, pulling new data"
    (cd $DATA_DIR && git checkout master && git pull)
fi

# Get reference repository commit id
DATA_ID=`cat $DATA_ID_FILE`

# Checkout data referenced by id file
./scripts/getdata $DATA_ID

