#!/bin/bash
#
# Copyright (C) 2013 Anders Logg and Martin Sandve Alnaes
#
# This file is part of FFC.
#
# FFC is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FFC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with FFC. If not, see <http://www.gnu.org/licenses/>.
#
# Modified by Johannes Ring, 2013-04-23
#
# First added:  2013-04-22
# Last changed: 2013-08-20
#
# This script downloads the reference data for the FFC regression tests
# and updates to the reference data version specified by the data id file.

# Parameters
source ./scripts/parameters

# Get updated reference repository
./scripts/getreferencerepo
if [ $? -ne 0 ]; then
    exit 1
fi

# Checkout data referenced by id file
./scripts/getdata
if [ $? -ne 0 ]; then
    exit 1
fi
