#!/usr/bin/env python

# Copyright (C) 2005-2006 Anders Logg
# Licensed under the GNU GPL Version 2

from time import time
from commands import *

# Run benchmark
t = time()
getoutput("../bin/ffc NavierStokes.form")
t1 = time() - t

# Run benchmark
t = time()
getoutput("../bin/ffc Stabilization.form")
t2 = time() - t

# Write report
print "Navier-Stokes: %.3f seconds" % t1
print "Stabilization: %.3f seconds" % t2
print "-----------------------------------"
