#!/usr/bin/env python

# Copyright (C) 2005-2006 Anders Logg
# Licensed under the GNU GPL Version 2

from timing import *
from commands import *

# Run benchmark
start()
getoutput("../bin/ffc NavierStokes.form")
finish()
t1 = milli() / 1000.0;

# Run benchmark
start()
getoutput("../bin/ffc Stabilization.form")
finish()
t2 = milli() / 1000.0;

# Write report
print "Navier-Stokes: %.3f seconds" % t1
print "Stabilization: %.3f seconds" % t2
print "-----------------------------------"
