#!/usr/bin/env python

# Copyright (c) 2005 Anders Logg (logg@tti-c.org)
# Licensed under the GNU GPL Version 2

from timing import *
from commands import *

# Run benchmark
start()
getoutput("../bin/ffc ../demo/NavierStokes.form")
finish()
t = milli() / 1000.0;

# Write report
print "Navier-Stokes: %.1f seconds" % t
print "-----------------------------------"
