#!/usr/bin/env python

# Copyright (C) 2005-2006 Anders Logg
# Licensed under the GNU GPL version 3 or any later version

from time import time
from commands import *

# Run benchmark
t = time()
getoutput("../scripts/ffc NavierStokes.form")
t1 = time() - t

# Run benchmark
t = time()
#getoutput("../bin/ffc Stabilization.form")
t2 = time() - t

# Write report
print "Navier-Stokes: %.3f seconds" % t1
#print "Stabilization: %.3f seconds" % t2
print "Stabilization: too much"
print ""
print "remove_unused() is *very* slow but this"
print "will be fixed in a future release"
print "-----------------------------------"
