# Copyright (C) 2025 Chris Richardson and Paul T. Kühner
#
# This file is part of FFCx.(https://www.fenicsproject.org)
#
# SPDX-License-Identifier:    LGPL-3.0-or-later
"""Templates for C++ file output."""

declaration_pre = """
// This code conforms with the UFC specification version {ufcx_version}
// and was automatically generated by FFCx version {ffcx_version}.
//
// This code was generated with the following options:
//
{options}

#pragma once

#include <complex>
#include <cstdint>
#include <cmath>
#include <vector>

#include <ufcx.h>

#if defined(_MSC_VER)
#   define RESTRICT __restrict
#else
#   define RESTRICT __restrict__
#endif

"""

declaration_post = """
"""

# TODO: remove? we only support a hpp for C++.
implementation_pre = """
// This code conforms with the UFC specification version {ufcx_version}
// and was automatically generated by FFCx version {ffcx_version}.
//
// This code was generated with the following options:
//
{options}

#include <cmath>
#include <ufcx.h>
{extra_includes}

"""

implementation_post = ""
