#!/usr/bin/env python
#
# This script cleans the FFC JIT cache

__author__ = "Anders Logg (logg@simula.no)"
__date__ = "2008-01-02 -- 2008-09-03"
__copyright__ = "Copyright (C) 2008 Anders Logg"
__license__  = "GNU GPL version 3 or any later version"

import sys

print "ffc-clean is deprecated, use instant-clean instead."
sys.exit(1)
