#!/bin/sh

# This script compiles and verifies all forms in the demo directory.

cd src/demo

for f in *.form; do
    PREFIX=`echo $f | cut -d'.' -f1`
    rm -f $PREFIX.h
    if [ $f != 'Stabilization.form' ]; then
      ../bin/ffc $f
      if [ -f $PREFIX.h ]; then
	  echo "Form $f compiled"
      else
	  echo "*** Unable to compile $f"
	  exit 1
      fi
    fi
done

# Compile one of the forms with optimization
../bin/ffc -O Optimization.form
if [ -f Optimization.h ]; then
    echo "Form Optimization.form compiled"
else
    echo "*** Unable to compile Optimization.form"
    exit 1
fi

echo ""
echo "All forms compiled, verifying output..."
echo "---------------------------------------"
echo ""

for f in *.h; do
    echo "--- Verifying $f ---"
    diff ../reference/$f $f
done
