"Code generation for the UFC 1.0 format with DOLFIN"

__author__ = "Anders Logg (logg@simula.no)"
__date__ = "2007-03-24 -- 2008-10-23"
__copyright__ = "Copyright (C) 2007-2008 Anders Logg"
__license__  = "GNU GPL version 3 or any later version"

# Modified by Kristian B. Oelgaard 2008
# Modified by Dag Lindbo, 2008

# Python modules
import os

# UFC code templates
from ufc import *

# FFC common modules
from ffc.common.utils import *
from ffc.common.debug import *
from ffc.common.constants import *

# FFC language modules
from ffc.compiler.language.restriction import *
from ffc.compiler.language.integral import *

# FFC format modules
import ufcformat

# Specify formatting for code generation
format = ufcformat.format

def init(options):
    "Initialize code generation for given options"
    ufcformat.init(options)

def write(generated_forms, prefix, options):
    "Generate UFC 1.0 code with DOLFIN wrappers for a given list of pregenerated forms"

    # Strip directory names from prefix and add output directory
    prefix = prefix.split(os.path.join(' ',' ').split()[0])[-1]
    full_prefix = os.path.join(options["output_dir"], prefix)
    
    # Generate code for header
    output = ""
    output += generate_header(prefix, options)
    output += "\n"

    if not options["split_implementation"]:

        debug("Generating code for UFC 1.0 with DOLFIN wrappers")

        # Generate UFC code
        output += ufcformat.generate_ufc(generated_forms, "UFC_" + prefix, options, "combined")

        # Generate code for DOLFIN wrappers
        output += __generate_dolfin_wrappers(generated_forms, prefix, options)

        # Generate code for footer
        output += generate_footer(prefix, options)

        # Write file
        filename = "%s.h" % full_prefix
        file = open(filename, "w")
        file.write(output)
        file.close()
        debug("Output written to " + filename)

    else:
        
        debug("Generating code for UFC 1.0 with DOLFIN wrappers, split header and implementation")

        # UFC declarations and DOLFIN wrappers ---------------------------------

        # Generate UFC code
        output += ufcformat.generate_ufc(generated_forms, "UFC_" + prefix, options, "header")

        # Generate code for DOLFIN wrappers
        output += __generate_dolfin_wrappers(generated_forms, prefix, options)

        # Generate code for footer
        output += generate_footer(prefix, options)

        # Write file
        filename = "%s.h" % full_prefix
        file = open(filename, "w")
        file.write(output)
        file.close()
        debug("Output written to " + filename)

        # UFC implementations --------------------------------------------------
        output = ""
        output += "#include \"%s.h\""%prefix

        # Generate UFC code
        output += ufcformat.generate_ufc(generated_forms, "UFC_" + prefix, options, "implementation")

        # Write file
        filename = "%s.cpp" % full_prefix
        file = open(filename, "w")
        file.write(output)
        file.close()
        debug("Output written to " + filename)

def generate_header(prefix, options):
    "Generate file header"

    # Check if BLAS is required
    if options["blas"]:
        blas_include = "\n#include <cblas.h>"
        blas_warning = "\n// Warning: This code was generated with '-f blas' and requires cblas.h."
    else:
        blas_include = ""
        blas_warning = ""
        
    return """\
// This code conforms with the UFC specification version 1.0
// and was automatically generated by FFC version %s.%s
//
// Warning: This code was generated with the option '-l dolfin'
// and contains DOLFIN-specific wrappers that depend on DOLFIN.

#ifndef __%s_H
#define __%s_H

#include <cmath>
#include <stdexcept>
#include <fstream>
#include <ufc.h>%s
""" % (FFC_VERSION, blas_warning, prefix.upper(), prefix.upper(), blas_include)

def generate_footer(prefix, options):
    "Generate file footer"
    return """\
#endif
"""

def __generate_dolfin_wrappers(generated_forms, prefix, options):
    "Generate code for DOLFIN wrappers"

    output = """\
// DOLFIN wrappers

namespace dolfin
{
  class FunctionSpace;
  class Function;
}

#include <dolfin/fem/Form.h>

"""
    
    # We generate two versions of all constructors, one using references (_r)
    # and one using shared pointers (_s)

    add_function_space_r = """\
    std::tr1::shared_ptr<dolfin::FunctionSpace> _V%d(&V%d, dolfin::NoDeleter<dolfin::FunctionSpace>());
    function_spaces.push_back(_V%d);"""

    add_function_space_s = """\
    function_spaces.push_back(V%d);"""

    add_coefficient_r =  """\
    std::tr1::shared_ptr<dolfin::Function> _v%d(&v%d, dolfin::NoDeleter<dolfin::Function>());
    coefficients.push_back(_v%d);"""

    add_coefficient_s =  """\
    coefficients.push_back(v%d);"""

    for i in range(len(generated_forms)):
        (form_code, form_data) = generated_forms[i]
        form_prefix = ufcformat.compute_prefix(prefix, generated_forms, i, options)
        constructor_args_r  = ", ".join(["dolfin::FunctionSpace& V%d" % i for i in range(form_data.rank)] +
                                        ["dolfin::Function& v%d" % i for i in range(form_data.num_coefficients)])
        constructor_args_s  = ", ".join(["std::tr1::shared_ptr<dolfin::FunctionSpace> V%d" % i for i in range(form_data.rank)] +
                                        ["std::tr1::shared_ptr<dolfin::Function> v%d" % i for i in range(form_data.num_coefficients)])
        constructor_body_r  = "\n".join([add_function_space_r % (i, i, i) for i in range(form_data.rank)])
        constructor_body_s  = "\n".join([add_function_space_s % i for i in range(form_data.rank)])
        if form_data.rank > 0:
            constructor_body_r += "\n\n"
            constructor_body_s += "\n\n"
        constructor_body_r += "\n".join([add_coefficient_r % (i, i, i) for i in range(form_data.num_coefficients)])
        constructor_body_s += "\n".join([add_coefficient_s % i for i in range(form_data.num_coefficients)])
        if form_data.num_coefficients > 0:
            constructor_body_r += "\n\n"
            constructor_body_s += "\n\n"
        constructor_body_r += "    _ufc_form = new UFC_%s();\n\n" % form_prefix
        constructor_body_s += "    _ufc_form = new UFC_%s();\n\n" % form_prefix
        constructor_body_r += "    check();"
        constructor_body_s += "    check();"
        output += """\
class %s : public dolfin::Form
{
public:

  %s(%s) : dolfin::Form()
  {
%s
  }

  %s(%s) : dolfin::Form()
  {
%s
  }

};

""" % (form_prefix,
       form_prefix, constructor_args_r, constructor_body_r,
       form_prefix, constructor_args_s, constructor_body_s)

    return output
