.TH "FFC" 1

.SH NAME
FFC - the FEniCS Form Compiler

.SH SYNOPSIS
.B ffc
[-h] [-l language] [-c license] input.form ...

.SH DESCRIPTION
Compile multilinear forms into efficient low-level code.

The FEniCS Form Compiler FFC accepts as input one or more files each
specifying one or more multilinear forms and compiles the given forms
into efficent low-level code for automatic assembly of the tensors
representing the multilinear forms. In particular, FFC compiles a pair
of bilinear and linear forms defining a variational problem into code
that can be used to efficiently assemble the corresponding linear
system.

By default, FFC generates C++ code for DOLFIN, but this can be changed
by specifying a different output language (option -l). It is also
possible to add new output languages to FFC.

For a full description of the FFC, including a specification of the
form language used to define the multilinear forms, see the FFC user
manual available on the FEniCS web page: http://www.fenics.org/

.SH OPTIONS
.TP
\fB\-h\fR
display help text and exit
.TP
\fB\-l\fR language, \fB\-\-language\fR language
specify output language, one of 'c++' (default), 'latex', 'raw' or 'ase'
.TP
\fB\-c\fR licence, \fB\-\-license\fR license
specify license for generated code (default is GPL)

.SH BUGS
.TP
Send comments, questions, bug reports etc. to ffc-dev@fenics.org.

.SH AUTHOR
Anders Logg (logg@tti-c.org)
